title: CUPID - for joyful code
theme: github.com/thingsym/hugo-theme-techdoc
baseURL: https://cupid.dev/
languageCode: en-GB

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

menu_exclusion:
  # path name excluded from documentation menu
  - posts

params:
  menu_style: open-menu
  custom_font_color: ''
  custom_background_color: ''
