# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL = 'https://cupid.dev/'
languageCode = 'en-GB'
title = 'CUPID—for joyful code'
theme = 'github.com/alex-shpak/hugo-book'

# Book configuration
# disablePathToLower = false
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

# [languages.ru]
#   languageName = 'Russian'
#   contentDir = 'content.ru'
#   weight = 2

# [languages.zh]
#   languageName = 'Chinese'
#   contentDir = 'content.zh'
#   weight = 3

# [menu]
# [[menu.before]]
# [[menu.after]]
#   name = "Github"
#   url = "https://github.com/alex-shpak/hugo-book"
#   weight = 10

# [[menu.after]]
#   name = "Hugo Themes"
#   url = "https://themes.gohugo.io/hugo-book/"
#   weight = 20

[permalinks]
docs = "/:slug/"

[params]
  BookTheme = 'auto'
#   BookTheme = 'light'
  BookToC = true
  # BookLogo = 'logo.png'
  BookSection = 'docs'

  BookRepo = 'https://github.com/cupiddev/cupiddev-website'
  BookCommitPath = 'commit'

  BookDateFormat = '2 Jan 2006'

  BookSearch = true
  BookComments = true
  BookPortableLinks = true
  BookServiceWorker = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables a drop-down menu for translations only if a translation is present.
  BookTranslatedOnly = false
