name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      # with:
      #   submodules: false

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@v1
      with:
        go_version: 1.17
        hugo_extended: true
        hugo_version: 0.92.1
      env:
        # HUGO_VERSION: 0.92.1
        # HUGO_EXTENDED: true
        # GO_VERSION: 1.17
        TARGET_REPO: cupiddev/cupiddev.github.io
        TARGET_BRANCH: main
        TOKEN: ${{ secrets.WEBSITE_DEPLOY_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # CNAME: www.jameswright.xyz
