name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        submodules: false

    # - name: Install go
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: '^1.17.6'

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@v1.13.0
      env:
        HUGO_VERSION: 0.92.1
        HUGO_EXTENDED: true
        GO_VERSION: 1.17.6
        TARGET_REPO: cupiddev/cupiddev.github.io
        TARGET_BRANCH: main
        TOKEN: ${{secrets.TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        # CNAME: www.jameswright.xyz
